### ISSUE TITLE
Can't browse/find emails 

### ISSUE THREAD

**Issue by funbben** [wolfgangasdf/gmail-attachment-remover#2]
Hi,
When I Click "Find emails" I get an error message "Gmail]/All Mail not found" (see log below)"
Probably a language issue since I have a french account.
I can get gmail folder list (see log below)

regards

```

============= Application log ==================== 
Get all gmail folders...
(re)connecting...
 connecting to gmail...
connected: true

.Archi
.BoisJoli
.CNP
.DRC
.EVEN
.FQP
.Famille
.Frat
.GROS
.GenEnt
.INBOX
.Inde
.Job
.Logica
.Notes
.PM
.RESSORT
.Scoob
.Solutec
.VdN
.[Gmail]
..[Gmail]/Brouillons
..[Gmail]/Corbeille
..[Gmail]/Important
..[Gmail]/Messages envoyￃﾩs
..[Gmail]/Spam
..[Gmail]/Suivis
..[Gmail]/Tous les messages
Get all gmail folders finished!
Find requested emails with attachments...
(re)connecting...
 connecting to gmail...
connected: true
onfailed: [Gmail]/All Mail not found
jakarta.mail.FolderNotFoundException: [Gmail]/All Mail not found
	at com.sun.mail.imap.IMAPFolder.checkExists(IMAPFolder.java:431)
	at com.sun.mail.imap.IMAPFolder.open(IMAPFolder.java:1044)
	at com.sun.mail.imap.IMAPFolder.open(IMAPFolder.java:977)
	at sgar.GmailStuff$$anon$1.call(GmailStuff.scala:108)
	at sgar.GmailStuff$$anon$1.call(GmailStuff.scala:102)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.concurrent.Service.lambda$executeTask$6(Service.java:727)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.concurrent.Service.lambda$executeTask$7(Service.java:726)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Exception [Gmail]/All Mail not found
jakarta.mail.FolderNotFoundException: [Gmail]/All Mail not found
	at com.sun.mail.imap.IMAPFolder.checkExists(IMAPFolder.java:431)
	at com.sun.mail.imap.IMAPFolder.open(IMAPFolder.java:1044)
	at com.sun.mail.imap.IMAPFolder.open(IMAPFolder.java:977)
	at sgar.GmailStuff$$anon$1.call(GmailStuff.scala:108)
	at sgar.GmailStuff$$anon$1.call(GmailStuff.scala:102)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.concurrent.Service.lambda$executeTask$6(Service.java:727)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.concurrent.Service.lambda$executeTask$7(Service.java:726)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by wolfgangasdf** [comment]
Hi, check out the new version, you should now be able to change the folder names.

**Comment by funbben** [comment]
Thanks for your quick reply. I Can now connect, and find emails.
However I can't seem to find ALL emails.
with "larger:10M" gmail display 67 emails GAR sent back 0 email
with "larger:8M" gmail display 144 emails GAR sent back 1 email

Also, I successfully removed some attachment from an email. However it took a very longue time (1 min)

**Comment by wolfgangasdf** [comment]
Hi, I use e.g. "size:5000KB has:attachment" and it works, I don't know why it wouldn't if you use now "Tous les messages" for "All Mail" (and if this contains really all mails). Also play with "limit # messages" and "minimum attachment size".
Speed: Yes it is nearly unusably slow, I sometimes I let it run for a day. There is nothing that can be done if one wants full backups (google bandwidth limits). If I would have time, I would implement a method without backup that doesn't download the full emails, but this requires thorough testing, see [source](https://github.com/wolfgangasdf/gmail-attachment-remover/blob/49d775083faf7c14bf00de2b154ee47489fcfe5b/src/main/scala/sgar/GmailStuff.scala#L151).

**Comment by wolfgangasdf** [comment]
this was implemented, closing for now.
