### ISSUE TITLE
"Error communicating with gmail   3 >= 2"

### ISSUE THREAD

**Issue by pakal** [wolfgangasdf/gmail-attachment-remover#6]
I launched this program on my gmail a first time and it went well  :)

But now when i retried with smaller emails as targets, "size:1MB has:attachment older_than:8m -in:inbox", it begins the removal of attachments on the found emails, and then crashes with this traceback below, and with a popup saying "Error communicating with gmail   3 >= 2" ; tried several times, same message.

I have no idea what has made this bug appear just now.

```
----- Re-connected!
[1/85] gmid=1689410594373094364 subj=Candidature :  Chargￃﾩ de projet communication et audiovisuel H/F  date=Wed Jan 20 13:57:47 CET 2021
backup message...
  backupfile=P:\Messagerie\GMAIL-ATTACHMENT-REMOVER-BACKUPS\1689410594373094364.msg
re-creating message...
remove attachments...
onfailed: 3 >= 2
java.lang.ArrayIndexOutOfBoundsException: 3 >= 2
	at java.base/java.util.Vector.elementAt(Unknown Source)
	at jakarta.mail.Multipart.removeBodyPart(Multipart.java:184)
	at jakarta.mail.internet.MimeMultipart.removeBodyPart(MimeMultipart.java:395)
	at sgar.GmailStuff$$anon$2.$anonfun$call$8(GmailStuff.scala:237)
	at sgar.GmailStuff$$anon$2.$anonfun$call$8$adapted(GmailStuff.scala:237)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
	at sgar.GmailStuff$$anon$2.$anonfun$call$7(GmailStuff.scala:237)
	at sgar.GmailStuff$$anon$2.$anonfun$call$7$adapted(GmailStuff.scala:191)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
	at sgar.GmailStuff$$anon$2.call(GmailStuff.scala:191)
	at sgar.GmailStuff$$anon$2.call(GmailStuff.scala:181)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1399)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.concurrent.Service.lambda$executeTask$6(Service.java:724)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.concurrent.Service.lambda$executeTask$7(Service.java:723)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Exception 3 >= 2
java.lang.ArrayIndexOutOfBoundsException: 3 >= 2
	at java.base/java.util.Vector.elementAt(Unknown Source)
	at jakarta.mail.Multipart.removeBodyPart(Multipart.java:184)
	at jakarta.mail.internet.MimeMultipart.removeBodyPart(MimeMultipart.java:395)
	at sgar.GmailStuff$$anon$2.$anonfun$call$8(GmailStuff.scala:237)
	at sgar.GmailStuff$$anon$2.$anonfun$call$8$adapted(GmailStuff.scala:237)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
	at sgar.GmailStuff$$anon$2.$anonfun$call$7(GmailStuff.scala:237)
	at sgar.GmailStuff$$anon$2.$anonfun$call$7$adapted(GmailStuff.scala:191)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
	at sgar.GmailStuff$$anon$2.call(GmailStuff.scala:191)
	at sgar.GmailStuff$$anon$2.call(GmailStuff.scala:181)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1399)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.concurrent.Service.lambda$executeTask$6(Service.java:724)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.concurrent.Service.lambda$executeTask$7(Service.java:723)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by wolfgangasdf** [comment]
Thanks for your report, sorry for radio silence - I could not reproduce your issue but I had a suspicion, however, since the logic got messed up over the years I needed some time to clean it, now there is a new version, probably this is fixed, too :-) so I close the issue for now feel free to reopen!
